name: Hello VoiceOver

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-voiceover:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Guidepup Setup
        uses: guidepup/setup-action@0.1.3
      - run: yarn install --frozen-lockfile
      - run: npx ts-node ./examples/hello-voiceover/index.ts
