name: Test2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
